services:
  - type: web
    name: todolist-api
    env: java
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/ToDo-0.0.1-SNAPSHOT.jar
    envVars:
      - key: PORT
        value: 8080
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: JWT_SECRET
        sync: false  # This will be set manually in Render dashboard
      - key: JWT_ENABLED
        value: true
      - key: SECURITY_PASSWORD_PEPPER
        sync: false  # This will be set manually in Render dashboard
    plan: free
    autoDeploy: true
    disk:
      name: todolist-disk
      mountPath: /app/logs
      sizeGB: 1